name: Addition_Reusable_workflow
on: 
 workflow_dispatch:
 workflow_call:

jobs:
 test:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3
   - run: |
      echo ${{vars.name}}
      echo "suraj=16" >> $GITHUB_ENV
      echo ${{ env.suraj }}
      env
     
 
