name: Addition_Reusable_workflow
on: 
 workflow_dispatch:
 workflow_call:

jobs:
 test:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3
   - run: |
      echo ${{vars.name}}
      tests=16
      failures=2

      # set them as GitHub ENV variables
      echo "Tests=$tests" >> $GITHUB_ENV
      echo "Failures=$failures" >> $GITHUB_ENV

      # retrieve these GitHub ENV variables
      echo "${{ env.Failures }} out of ${{ env.Tests }} tests failed on CI"
     
 
